micronaut:
  application:
    name: apiGateway
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages: 'aws.fs.gateway.core.entities'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: validate